Add async sampling POC
EricLBuehler/mistral.rs pull request #198
Opened 2024-04-23 03:57 UTC by lucasavila00

I took a stab at something similar to https://github.com/EricLBuehler/mistral.rs/pull/195

The code is not ready for merge, but it should be ready to be benchmarked.

If we like this approach, I can organize the code.

For me:

``` 
master
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+
| model                              | backend | test  | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 64 | 31.429±0.152 | 31.819±0.154 |           4 |   125.714966 |
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+

this PR
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+
| model                              | backend | test  | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 64 | 31.963±0.184 | 31.288±0.181 |           4 |   127.850845 |
+------------------------------------+---------+-------+--------------+--------------+-------------+--------------+
```

2024-04-23 04:01 UTC, lucasavila00 commented on mistralrs-core/src/pipeline/mod.rs
> +    .await?;
run this in a threadpool, but using async and await for control flow

2024-04-26 00:43 UTC, EricLBuehler commented
@lucasavila00, thanks for your work here. I think we definitely need to pursue the throughput decrease as the batch increase. I like the idea of async being incorporated, did this not work out?

2024-04-26 01:01 UTC, lucasavila00 commented
@EricLBuehler It had mixed results.

On bs=8 it improved from 5ms to 2ms.

But on bs=1 it got worse, from 0.8ms to 1.2ms.

Clippy raised an issue of a non-async mutex being held across an await point.

The best fix for it would be to use an async aware mutex? Or drop the lock a lot of times and re-lock when needed?

I'm still learning async rust and don't feel confident enough to work on this MR yet, as it requires defining the overall async structure for the engine.

Also, profiling CPU code became harder (eg: samply profiler). Only the nvidia profiler showed interpretable results.

2024-04-26 01:04 UTC, EricLBuehler commented
> On bs=8 it improved from 5ms to 2ms.
Great! Perhaps we could profile it and see when the performance gains go away, and use this then.
> Clippy raised an issue of a non-async mutex being held across an await point.
We could use [this type](https://doc.servo.org/tokio/sync/struct.Mutex.html).

I think this sort of structure is very interesting, I'll take a look in the next few days. Thanks for working on it.

2024-04-26 03:42 UTC, lucasavila00 commented
I'll leave it open, so it picks up my commits.

I just fixed the clippy issue, by not holding the lock across awaits.

2024-04-26 04:27 UTC, lucasavila00 commented
@EricLBuehler cargo test fails because it can't download the mistral tokenizer from HF.

Any chance the CI account does not have access to the model, which has been recently locked (locked like llama where one needs to request access)

2024-04-26 04:32 UTC, lucasavila00 commented
> Great! Perhaps we could profile it and see when the performance gains go away, and use this then.

I implemented it in the last commit. It only uses the async pool if there's more than one batch. Then, the performance loss is gone.

It means that the async code is free if not used.

2024-04-26 06:12 UTC, lucasavila00 commented
I added 2 nvidia profiler screenshots to the main PR body.

2024-04-26 08:56 UTC, EricLBuehler commented
@lucasavila00 

> cargo test fails because it can't download the mistral tokenizer from HF.

I set the `HF_TOKEN` secret during CI: 
> https://github.com/EricLBuehler/mistral.rs/blob/9ec90a40949efe9c68828c048da136874d1ba2f1/.github/workflows/ci.yml#L49

2024-04-26 19:22 UTC, EricLBuehler commented
@lucasavila00, it looks like there are some merge conflicts.

2024-04-26 19:32 UTC, lucasavila00 commented
> @lucasavila00, it looks like there are some merge conflicts.

I'm fixing it

2024-04-26 19:47 UTC, lucasavila00 commented on mistralrs-core/src/engine/mod.rs
> +        let logits_seq = logits.to_device(&Device::Cpu)?.chunk(seqs_len, 0)?;
Now that we do a synchronization before we start sampling, we can get statistics about sampling speed.

Basically reverting https://github.com/EricLBuehler/mistral.rs/pull/151

2024-04-26 20:14 UTC, lucasavila00 commented
Master

```
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 58.712±0.644 | 17.034±0.190 |           1 |    58.712006 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 45.956±0.805 | 21.766±0.380 |           2 |      91.9128 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 29.011±0.321 | 34.473±0.388 |           4 |     116.0458 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 15.469±0.388 | 64.685±1.639 |           8 |    123.75505 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
```


This

```
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 58.752±0.501 | 17.022±0.147 |           1 |    58.752266 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 48.121±0.124 | 20.781±0.053 |           2 |     96.24125 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 30.030±0.020 | 33.300±0.022 |           4 |    120.12018 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| model                              | backend | test   | t/s          | ms/t         | concurrency | throughput/s |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
| mistralai/Mistral-7B-Instruct-v0.1 | CUDA    | tg 128 | 16.839±0.008 | 59.384±0.027 |           8 |    134.71562 |
+------------------------------------+---------+--------+--------------+--------------+-------------+--------------+
```

2024-04-27 09:50 UTC, EricLBuehler commented
@lucasavila00, this looks good. However, I think there is one more merge conflict.

2024-04-27 10:11 UTC, EricLBuehler requested changes
This looks good. I think I made some mistakes when doing the conflict resolution, so I've marked them.

2024-04-27 10:11 UTC, EricLBuehler commented on mistralrs-core/src/pipeline/mod.rs
> +use crate::DeviceMapMetadata;
We should remove this, it is causing the error.
```suggestion

```

2024-04-27 10:11 UTC, EricLBuehler commented on mistralrs-core/src/pipeline/mod.rs
>  use crate::{get_bias_if_not_allowed, sampler::Logprobs, sequence::SequenceRecognizer};
We should remove this line, the imports are unused.
```suggestion
```

2024-04-28 01:06 UTC, EricLBuehler approved these changes
Looks good, thank you for adding this!

2024-04-28 01:06 UTC, EricLBuehler commented
@lucasavila00, I think there are unfortunately still some merge conflicts.

2024-04-28 01:30 UTC, lucasavila00 commented
@EricLBuehler please consider squashing this MR

Or please let me know if I should squash it

2024-04-28 01:34 UTC, EricLBuehler approved these changes

2024-04-28 01:36 UTC, merged

2024-04-28 01:37 UTC, EricLBuehler commented
@lucasavila00 thank you for adding this!